# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='Accept',
            new_name='accept',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='Contact',
            new_name='cont_app',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='Num_people',
            new_name='num_people',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='Rearr',
            new_name='rearr',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Contact',
            new_name='contact_req',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='From',
            new_name='path_from',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='To',
            new_name='path_to',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Popl',
            new_name='popl',
        ),
    ]
