# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_auto_20171027_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='contact_req',
            new_name='cont_req',
        ),
    ]
